Feature/products
Decembric/icecream-landing-page pull request #1
Opened 2022-09-17 12:48 UTC by watchfilm88

HTML на проверку, CSS еще работе

2022-09-17 12:53 UTC, Decembric commented on src/partials/products.html
> +    <label for=""
Тег label здесь не используется. Достаточно параграфа

2022-09-17 12:56 UTC, watchfilm88 commented on src/partials/products.html
> +    <label for=""
В третьем комите все исправлено

2022-09-17 13:02 UTC, Decembric commented on src/partials/products.html
> +    <label for=""
Увидел

2022-09-17 13:50 UTC, Decembric requested changes

2022-09-17 13:50 UTC, Decembric commented on src/sass/layouts/_products.scss
> +  font-family: 'Montserrat';
Можно не указывать font-family: Montserrat, так как оно у нас в body указано

2022-09-19 07:43 UTC, Decembric approved these changes

2022-09-19 07:44 UTC, merged